---
abstract: 'A recursive DNS client for POE'
author:
  - 'Chris Williams <chris@bingosnet.co.uk>'
build_requires:
  File::Spec: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Test::More: '0.47'
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.019, CPAN::Meta::Converter version 2.141520'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: POE-Component-Client-DNS-Recursive
requires:
  IO::Socket::IP: '0.29'
  Net::DNS: '0.69'
  Net::DNS::Packet: '0'
  Net::IP::Minimal: '0'
  POE: '1.004'
  Socket: '2.013'
  perl: '5.006'
resources:
  homepage: https://github.com/bingos/poe-component-client-dns-recursive
  repository: https://github.com/bingos/poe-component-client-dns-recursive.git
version: '1.08'
